.TH DNSIP 1 "2026-07-23" "rgbdns 0.1.0" "User Commands"
.SH NAME
dnsip \- look up IPv4 addresses
.SH SYNOPSIS
.B dnsip
.RI [ name ...]
.SH DESCRIPTION
Performs recursive A queries and prints the IPv4 addresses for each name, one
input name per output line.
.SH SEE ALSO
.BR dnsipq (1),
.BR dnsip6 (1)
