.TH DNSIP6 1 "2026-07-23" "rgbdns 0.6.0" "User Commands"
.SH NAME
dnsip6 \- look up IPv6 addresses
.SH SYNOPSIS
.B dnsip6
.RI [ name ...]
.SH DESCRIPTION
Performs recursive AAAA queries and prints the IPv6 addresses for each name,
one input name per output line.
.SH SEE ALSO
.BR dnsip6q (1),
.BR dnsip (1)
