.TH DNSNAME 1 "2026-07-23" "rgbdns 0.2.0" "User Commands"
.SH NAME
dnsname \- look up names for IPv4 addresses
.SH SYNOPSIS
.B dnsname
.RI [ address ...]
.SH DESCRIPTION
Performs recursive in-addr.arpa PTR queries and prints the resulting names,
one input address per output line.
.SH SEE ALSO
.BR dnsfilter (1)
