.TH DNSQ 1 "2026-07-23" "rgbdns 0.6.1" "User Commands"
.SH NAME
dnsq \- send a non-recursive DNS query
.SH SYNOPSIS
.B dnsq
.I type name server
.SH DESCRIPTION
Sends a query of the named record type directly to a DNS server and prints a
structured representation of the response.  The server may include a port.
.SH SEE ALSO
.BR dnsqr (1),
.BR dnstrace (1)
