.TH DNSQR 1 "2026-07-23" "rgbdns 0.1.0" "User Commands"
.SH NAME
dnsqr \- perform a recursive DNS query
.SH SYNOPSIS
.B dnsqr
.I type name
.SH DESCRIPTION
Resolves the requested record type recursively using the system resolver and
prints a structured representation of the response.
.SH SEE ALSO
.BR dnsq (1),
.BR dnstrace (1)
