.TH DNSTXT 1 "2026-07-23" "rgbdns 0.6.0" "User Commands"
.SH NAME
dnstxt \- look up DNS text records
.SH SYNOPSIS
.B dnstxt
.RI [ name ...]
.SH DESCRIPTION
Performs recursive TXT queries and concatenates the chunks of each answer,
followed by a newline for each input name.
.SH SEE ALSO
.BR dnsqr (1)
