.TH PICKDNS-CONF 1 "2026-07-23" "rgbdns 0.2.0" "User Commands"
.SH NAME
pickdns-conf \- create a pickdns service directory
.SH SYNOPSIS
.B pickdns-conf
.I account log-account directory ip
.SH DESCRIPTION
Creates an absolute daemontools-style service directory with an empty data
file, Makefile, run script, environment, and logging setup.
.SH SEE ALSO
.BR pickdns (1),
.BR pickdns-data (1)
