.TH RBLDNS-CONF 1 "2026-07-23" "rgbdns 0.6.2" "User Commands"
.SH NAME
rbldns-conf \- create an rbldns service directory
.SH SYNOPSIS
.B rbldns-conf
.I account log-account directory ip base
.SH DESCRIPTION
Creates an absolute daemontools-style service directory with an empty data
file, Makefile, run script, BASE environment, and logging setup.
.SH SEE ALSO
.BR rbldns (1),
.BR rbldns-data (1)
