.TH TINYDNS-CONF 1 "2026-07-23" "rgbdns 0.6.0" "User Commands"
.SH NAME
tinydns-conf \- create a tinydns service directory
.SH SYNOPSIS
.B tinydns-conf
.I account log-account directory ip
.SH DESCRIPTION
Creates an absolute daemontools-style service directory, data file, Makefile,
record-addition helper scripts, environment, and logging setup.
.SH SEE ALSO
.BR tinydns (1),
.BR tinydns-data (1),
.BR tinydns-edit (1)
