.TH WALLDNS-CONF 1 "2026-07-23" "rgbdns 0.6.3" "User Commands"
.SH NAME
walldns-conf \- create a walldns service directory
.SH SYNOPSIS
.B walldns-conf
.I account log-account directory ip
.SH DESCRIPTION
Creates an absolute daemontools-style service directory with run script,
environment, and logging setup.
.SH SEE ALSO
.BR walldns (1)
