import { SignJWT, importPKCS8 } from "jose";

const api = "https://api.github.com";

function required(name: string) {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not configured`);
  return value;
}

async function installationToken() {
  const appId = required("GITHUB_APP_ID");
  const key = await importPKCS8(required("GITHUB_APP_PRIVATE_KEY").replaceAll("\\n", "\n"), "RS256");
  const now = Math.floor(Date.now() / 1000);
  const jwt = await new SignJWT({}).setProtectedHeader({ alg: "RS256" }).setIssuer(appId).setIssuedAt(now - 60).setExpirationTime(now + 540).sign(key);
  const response = await fetch(`${api}/app/installations/${required("GITHUB_INSTALLATION_ID")}/access_tokens`, { method: "POST", headers: { authorization: `Bearer ${jwt}`, accept: "application/vnd.github+json", "x-github-api-version": "2022-11-28" } });
  if (!response.ok) throw new Error(`GitHub installation token failed: ${response.status}`);
  return (await response.json() as { token: string }).token;
}

function repository() {
  const [owner, repo] = required("RGBDNS_REPOSITORY").split("/");
  if (!owner || !repo) throw new Error("RGBDNS_REPOSITORY must be owner/name");
  return { owner, repo, base: process.env.RGBDNS_BASE_BRANCH || "master" };
}

async function call<T>(token: string, path: string, init: RequestInit = {}) {
  const response = await fetch(`${api}${path}`, { ...init, headers: { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "content-type": "application/json", "x-github-api-version": "2022-11-28", ...init.headers } });
  if (!response.ok) throw new Error(`GitHub ${init.method || "GET"} ${path} failed: ${response.status} ${await response.text()}`);
  return response.json() as Promise<T>;
}

async function callVoid(token: string, path: string, init: RequestInit = {}) {
  const response = await fetch(`${api}${path}`, { ...init, headers: { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "content-type": "application/json", "x-github-api-version": "2022-11-28", ...init.headers } });
  if (!response.ok) throw new Error(`GitHub ${init.method || "GET"} ${path} failed: ${response.status} ${await response.text()}`);
}

export async function dispatchDnsDeployment() {
  const token = await installationToken();
  const { owner, repo, base } = repository();
  await callVoid(token, `/repos/${owner}/${repo}/actions/workflows/deploy-dns.yml/dispatches`, {
    method: "POST",
    body: JSON.stringify({ ref: base }),
  });
}

export async function readDeploymentFiles() {
  const token = await installationToken(); const { owner, repo, base } = repository();
  async function read(path: string) {
    const file = await call<{ content: string; sha: string }>(token, `/repos/${owner}/${repo}/contents/${path}?ref=${encodeURIComponent(base)}`);
    return { text: Buffer.from(file.content, "base64").toString("utf8"), sha: file.sha };
  }
  const [data, zones] = await Promise.all([read("rgbdns.data"), read("rgbdns.zones")]);
  return { token, owner, repo, base, data, zones };
}

export async function openDeploymentPullRequest(input: { token: string; owner: string; repo: string; base: string; data: { text: string; sha: string }; zones: { text: string; sha: string }; branch: string; title: string }) {
  const ref = await call<{ object: { sha: string } }>(input.token, `/repos/${input.owner}/${input.repo}/git/ref/heads/${encodeURIComponent(input.base)}`);
  await call(input.token, `/repos/${input.owner}/${input.repo}/git/refs`, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${input.branch}`, sha: ref.object.sha }) });
  for (const [path, file] of [["rgbdns.data", input.data], ["rgbdns.zones", input.zones]] as const) {
    await call(input.token, `/repos/${input.owner}/${input.repo}/contents/${path}`, { method: "PUT", body: JSON.stringify({ message: `Update ${path} from Wishfully`, content: Buffer.from(file.text).toString("base64"), sha: file.sha, branch: input.branch }) });
  }
  return call<{ html_url: string; number: number }>(input.token, `/repos/${input.owner}/${input.repo}/pulls`, { method: "POST", body: JSON.stringify({ title: input.title, head: input.branch, base: input.base, body: "Generated by Wishfully from verified domain manifests. Merge only after the DNS data validation check passes." }) });
}
