#!/bin/sh
set -e

if [ "$1" = remove ]; then
    deb-systemd-invoke stop rgbdns-query-report.timer \
        rgbdns-dnssec-publish.timer \
        rgbdns-dnssec-check.timer \
        rgbdns-secondary-sync.timer \
        rgbdns-secondary-sync.service \
        rgbdns-tinydns.service >/dev/null || true
fi

#DEBHELPER#

exit 0
