import { timingSafeEqual } from "node:crypto";
import { decryptSecret } from "@/lib/acme-secret";
import { db } from "@/lib/db";

export const runtime = "nodejs";

export async function GET(request: Request) {
  const expected = process.env.ACME_BUNDLE_TOKEN || ""; const supplied = request.headers.get("authorization")?.replace(/^Bearer /, "") || "";
  if (!expected || expected.length !== supplied.length || !timingSafeEqual(Buffer.from(expected), Buffer.from(supplied))) return new Response("Unauthorized\n", { status: 401 });
  const sql = db();
  const rows = await sql<Array<{ key_name: string; secret_ciphertext: string; secret_iv: string; name: string }>>`
    SELECT credential.key_name, credential.secret_ciphertext, credential.secret_iv, domain.name
      FROM acme_credentials AS credential JOIN domains AS domain ON domain.id = credential.domain_id
     WHERE credential.status = 'active' AND domain.status IN ('verified','pending_delegation','active') ORDER BY credential.key_name
  `;
  const lines = ["# Generated by Wishfully. Do not edit or commit.", ...rows.map((row) => `${row.key_name}\thmac-sha256.\t${decryptSecret(row.secret_ciphertext, row.secret_iv)}\t${row.name}.\t_acme-challenge.\t60`)];
  return new Response(lines.join("\n") + "\n", { headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" } });
}
